Add blog expanding DDEV maintainer team
ddev/ddev.com pull request #104
Opened 2023-09-27 23:23 UTC by rfay

## The Issue

New blog - Expanding DDEV Maintainer Team

2023-09-29 16:08 UTC, stasadev requested changes
Looks good! The only thing I noticed was the broken link style and typo.

2023-09-29 16:08 UTC, stasadev commented on src/content/blog/expanding-ddev-maintainer-team.md
> +- [**Platform.sh](http://Platform.sh)** pays Randy’s salary and provides benefits to him as an employee. That is an amazing benefit for this community and goes a long way! THANK YOU!
```suggestion
- **[Platform.sh](http://Platform.sh)** pays Randy’s salary and provides benefits to him as an employee. That is an amazing benefit for this community and goes a long way! THANK YOU!
```

2023-09-29 16:08 UTC, stasadev commented on src/content/blog/expanding-ddev-maintainer-team.md
> +Currently **[Randy Fay](https://github.com/rfay), [Simon Gilli](https://github.com/gilbertsoft) and [Stas Zuk](https://github.com/stasadev)** have maintainer privileges. Simon has made enormous contr
```suggestion
Currently **[Randy Fay](https://github.com/rfay), [Simon Gilli](https://github.com/gilbertsoft) and [Stas Zhuk](https://github.com/stasadev)** have maintainer privileges. Simon has made enormous contributions over the years and knows how to handle most maintainer roles. He has been periodically paid by the DDEV Foundation for his work, but his available time is sometimes spotty. Stas is new to the role after many, many important contributions. Financial arrangements are pending.
```

2023-09-30 13:01 UTC, rfay commented on src/content/blog/expanding-ddev-maintainer-team.md
> +Currently **[Randy Fay](https://github.com/rfay), [Simon Gilli](https://github.com/gilbertsoft) and [Stas Zuk](https://github.com/stasadev)** have maintainer privileges. Simon has made enormous contr
Glad you caught that. Sorry for the typo.

2023-09-30 13:01 UTC, rfay commented
Thanks for the review!

2023-09-30 14:39 UTC, merged