Add vite blog article
ddev/ddev.com pull request #115
Opened 2023-10-14 17:33 UTC by mandrasch

## The Issue

- introductionary article to vite needed for DDEV to help user

## How This PR Solves The Issue

- introduce chore concepts

## Manual Testing Instructions

## Automated Testing Overview

- no

## Related Issue Link(s)

## Release/Deployment Notes

2023-10-14 18:06 UTC, rfay commented
Yay!

2023-10-16 08:15 UTC, rfay commented
Thanks, just mark it ready to review when you're ready. Looks like there are just minor textlint complaints.

2023-10-23 21:22 UTC, mandrasch commented
> Thanks, just mark it ready to review when you're ready. Looks like there are just minor textlint complaints.

👍 will do. hope to finish it by the end of next week, maybe a week later. cheers!

2023-11-04 19:08 UTC, mandrasch commented
Hey @rfay,

I completed the article draft, hope it will be useful for the community.

Questions:

1. Should I choose / create an article image as well?
2. I couldn't find an example for Vite + DDEV + Gitpod - should we ask the community before publishing?
3. I couldn't find an example for Vite + DDEV + Drupal - should we ask the community before publishing?

Cheers! 👋

2023-11-06 21:03 UTC, rfay commented
Yay, thanks! Can you suggest any good reviewers? Will ask @tyler36 - could you take a look?

2023-11-07 00:15 UTC, tyler36 commented on src/content/blog/working-with-ddev-and-vite.md
> +type: "module"
Needs quotes (and comma) to be valid.

```suggestion
"type": "module",
```

2023-11-07 00:41 UTC, tyler36 commented
Went through the example, and was able to to follow along and get it working.
A couple of nitpicking things above.

I didn't try any of the framework guides.
Is it worth mensioning https://github.com/torenware/ddev-viteserve somewhere, or is this focused on do-it-yourself?

2023-11-07 00:44 UTC, tyler36 commented
And, of course, thank you for taking the time to write up the article. 

I know questions often come up on Discord about vite and DDEV and it's great to have a well-written and easy to follow guide to recommend to others.

Thank you @mandrasch !

2023-11-07 13:28 UTC, mandrasch commented
> Went through the example, and was able to to follow along and get it working. A couple of nitpicking things above. 

Nice, thanks so much for review! 👍 👍  I'll fix the typo with module later on.

> I didn't try any of the framework guides. Is it worth mensioning https://github.com/torenware/ddev-viteserve somewhere, or is this focused on do-it-yourself?

Good point / question. 👍 Also thought about it.

Personally I don't use viteserve because I want to run vite visible - and want to see my errors directly if a JS file has an error for example in the vite output. Therefore I just use `ddev npm run dev`. 

Most JS frameworks like sveltekit, nextjs, etc. work like that as far as I experience it: You run `npm run dev` when you want to develop locally (https://kit.svelte.dev/docs/creating-a-project) and you see build errors directly in the terminal.

The aspect of log output is adressed here https://github.com/torenware/ddev-viteserve/issues/20

I have much respect for torenwares hard work on this, but personally I don't want to complicate the introduction.

Maybe we could add a vite section on https://github.com/ddev/awesome-ddev, add available add-ons there and link to it? (Or somebody creates another article about viteserve)

Just thought about that maybe this current article could also be split in two parts:
- ddev and vite introduction (sample project)
- ddev and vite: framework + cms integration

🤔

2023-11-07 22:46 UTC, rfay reviewed
Thanks so much for this! It's going to be great. 

What do you think about using the photo of you as the main image?

2023-11-07 23:14 UTC, rfay requested changes
Thanks for this! 

I rebased and also made a number of small suggestions, you should be able to just accept the ones you're OK with by using the GitHub web interface.

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +## Working with DDEV and vite
```suggestion
## Using Vite with DDEV
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +
```suggestion
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +```
Is it important to say this? I would probably suggest removing it, as more-or-less off-topic?

```suggestion
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +1. Expose Vites development server port (default: `5173`)
```suggestion
1. Expose Vite's development server port (default: `5173`)
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +cd test-vite
```suggestion
mkdir test-vite && cd test-vite
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +_For more advanced examples, check out Vites guide [Scaffolding Your First Vite Project](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)._
```suggestion
_For more advanced examples, check out Vite's guide [Scaffolding Your First Vite Project](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)._
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +A quick reminder: Every npm command needs to be executed within the DDEV Docker containers for the project. Therefore we always need to use `ddev npm` (or `ddev yarn`).
```suggestion
A quick reminder: Every npm command needs to be executed within the DDEV web container, so we use `ddev npm` (or `ddev yarn`).
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +### 1. Expose the vite port
Shouldn't this just be 
```suggestion
### Expose the vite port
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +_Note: In other projects you might come across docker-compose-files in the .ddev/-folder which also take care of exposing the vite port. If you use `web_extra_exposed_ports`, you don't need these fil
```suggestion
_Note: In other tutorials or projects you may come across docker-compose-files in the .ddev/-folder which also take care of exposing the vite port. If you use `web_extra_exposed_ports`, you don't need these files._
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +- Also we need to tell vite to respond to all network request, not only the ones addressed to http://localhost:5173. This is done via `host: '0.0.0.0'`. You could also use `true`.
I didn't understand "You could also use `true`" so suggest removing that, it's not clear what it's referring to.
```suggestion
- Also we need to tell vite to respond to all network request, not only the ones addressed to http://localhost:5173. This is done via `host: '0.0.0.0'`. 
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +See Vites [Server Options](https://vitejs.dev/config/server-options.html) for all settings.
```suggestion
See Vite's [Server Options](https://vitejs.dev/config/server-options.html) for all settings.
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +Vite also optimizes images referenced in CSS. These are also loaded from Vites dev server for local production.
```suggestion
Vite also optimizes images referenced in CSS. These are also loaded from Vite's dev server for local production.
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +You can read Vites official guide for backend integration here:
```suggestion
You can read Vite's official guide for backend integration here: 
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +I found this plugin:
```suggestion
I found this module:
```

2023-11-07 23:14 UTC, rfay commented on src/content/blog/working-with-ddev-and-vite.md
> +Laravels Vite integration is a bit special, because it has its own npm integration with a so called `hot` file.
```suggestion
Laravel's Vite integration is a bit special, because it has its own npm integration with a so called `hot` file. 
```

2023-11-08 03:55 UTC, rfay commented
@mattstein doesn't allow me to use the word "simply". There should be an exception for you, but there's not :)

2023-11-08 03:55 UTC, rfay commented
Thanks for the graphic!

2023-11-08 04:02 UTC, mandrasch commented
> Thanks for the graphic!

Sure thing. 👍  (I used https://www.adobe.com/express/feature/image/remove-background and a canva template https://www.canva.com/templates/?query=youtube-thumbnail)

2023-11-08 04:06 UTC, mandrasch commented
@rfay thanks for review / fixes. from my point of view we're good to go. 👍

2023-11-08 13:24 UTC, merged

2023-11-08 13:24 UTC, rfay commented
Thanks so much!