Adds featured-sponsors-darkmode.svg to fix darkmode sponsors on ddev/ddev
ddev/ddev.com pull request #134
Opened 2023-11-04 02:14 UTC by bmartinez287

Adds featured-sponsors-darkmode.svg to fix dark mode sponsors on ddev/ddev

## The Issue
https://github.com/ddev/ddev/issues/5492

## How This PR Solves The Issue
This PR makes the asset available

2023-11-04 02:49 UTC, bmartinez287 commented
https://35a114ba.ddev-com-front-end.pages.dev/resources/featured-sponsors-darkmode.svg
https://35a114ba.ddev-com-front-end.pages.dev/resources/featured-sponsors.svg

2023-11-07 23:23 UTC, rfay requested changes
Well, it certainly looks fine, but how did you recreate the problem logos? That needs to be added to the README I guess unless you're permanently available for this task.

@mattstein thoughts?

2023-11-07 23:58 UTC, bmartinez287 commented
I basically used the same method I used on ddev.com on this. Most of the logos already existed except for a few that I was just inverting the colors.
The one that proved most challenging was Drupaleasy since it's a PNG but I got it done.

I use inkscape for all but drupaleasy to edit the SVG's then select all the letters icons and on the color pallete switch them to pure white and export the file with a new name. Inkscape is an open-source tool but any other's like illustrator can accomplish the same goal.

2023-11-08 00:04 UTC, bmartinez287 commented
I can be on the watch for those PRs and add them as needed. It takes a min or two if I have a laptop with me.

2023-11-08 00:13 UTC, rfay commented
It's never a rush. Thanks for your help with it. Could just turn the new-sponsor task over to you as well.

2023-11-08 00:40 UTC, bmartinez287 commented
Yeah, I'm down. If you get the files and share them as an issue I can add the PR for them

2023-11-08 02:00 UTC, mattstein requested changes
I didn’t realize you could use a `<picture>` element in a GitHub readme to solve the problem—cool!

I initially shied away from dark mode over logo management, but now that we’re here it might be worth standardizing the sponsor intake process and having a shared source for these so it’s not dependent on any one person hammering them out. I have a pile of logos in Figma I cleaned up for that first push, but I’m not sure what the most convenient place would be.

If we end up with clean, organization-approved SVG files then maybe it’s not a big deal. 🤷‍♂️

2023-11-08 03:45 UTC, bmartinez287 commented on src/pages/resources/featured-sponsors-darkmode.svg.js
mmm, that's an interesting idea. I left it like that for simplicity but I can see why that could be more maintainable. I will take a look and see what can be done with partials here.

2023-11-08 13:23 UTC, merged