Amplitude stats blog
ddev/ddev.com pull request #271
Opened 2024-11-03 19:22 UTC by rfay

## The Issue

* Amplitude stats blog
* Amplitude contributor training blog

2024-11-03 21:52 UTC, rpkoller commented
thanks for the changes. with the static images there is no more access to third party assets nor the creation of any cookies related to amplitude. from a gdpr perspective the cleaner solution.

2024-11-04 12:39 UTC, stasadev requested changes

2024-11-04 12:39 UTC, stasadev commented on src/content/blog/stats-on-ddev-usage-nov-2024.md
> +You can explore these yourself, ask for permission.** If you're a known community member I'll happily add your access to Amplitude to explore. There are many more things that can be done with this. S
```suggestion
**You can explore these yourself, ask for permission.** If you're a known community member I'll happily add your access to Amplitude to explore. There are many more things that can be done with this. See [Amplitude Contributor Training](amplitude-ddev-analytics-contributor-training.md).
```

2024-11-04 12:39 UTC, stasadev commented on src/content/blog/stats-on-ddev-usage-nov-2024.md
> +Here's an updated review of some DDEV usage stats. It's always fun to see some of these. Most of these charts are number from the past 7 days. And they are LIVE stats as you view.
```suggestion
Here's an updated review of some DDEV usage stats. It's always fun to see some of these. Most of these charts are number from the past 7 days (Oct 28 - Nov 3, 2024). And check out the LIVE stats link below each chart.
```

2024-11-04 17:10 UTC, rfay commented on src/content/blog/stats-on-ddev-usage-nov-2024.md
> +Here's an updated review of some DDEV usage stats. It's always fun to see some of these. Most of these charts are number from the past 7 days. And they are LIVE stats as you view.
```suggestion
Here's an updated review of some DDEV usage stats. It's always fun to see some of these. Most of these charts are from the past 7 days (Oct 28 - Nov 3, 2024). And check out the LIVE stats link below each chart.
```

2024-11-04 17:36 UTC, merged